name       : upower
version    : 1.90.0
release    : 18
source     :
    - https://gitlab.freedesktop.org/upower/upower/-/archive/v1.90.0/upower-v1.90.0.tar.gz : cb6028f095824422c59d98b3c9903e2eda2a96fc613f11824f0b6379de7efa2e
license    :
    - LGPL-2.0-or-later
component  : desktop.core
summary    : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description: |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
builddeps  :
    - pkgconfig(gudev-1.0)
    - pkgconfig(libusb-1.0)
    - docbook-xml
    - gtk-doc
setup      : |
    %apply_patches
    %meson_configure -Didevice=enabled -Dgtk-doc=false -Dman=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -m 00644 $pkgfiles/upower.tmpfiles $installdir/%libdir%/tmpfiles.d/upower.conf
    rm -rvf $installdir/var
