name       : upower
version    : 0.99.13
release    : 16
source     :
    - https://gitlab.freedesktop.org/upower/upower/uploads/177df5b9f9b76f25a2ad9da41aa0c1fa/upower-0.99.13.tar.xz : 5cad70f91540cc7dc121cb17e0ad645e5e663c8682f60a7be42ee38cd7b23d7a
license    :
    - LGPL-2.0-or-later
component  : desktop.core
summary    : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description: |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
builddeps  :
    - pkgconfig(gudev-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libimobiledevice-1.0)
    - docbook-xml
setup      : |
    %apply_patches
    %reconfigure --disable-static --with-idevice
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/upower.tmpfiles $installdir/%libdir%/tmpfiles.d/upower.conf
    rm -rvf $installdir/var
