name       : upower
version    : 1.90.2
release    : 20
source     :
    - https://gitlab.freedesktop.org/upower/upower/-/archive/v1.90.2/upower-v1.90.2.tar.gz : 5c4e736648f0c89d2368fbbe1e6fc0598a1565c4b435bade1d65e890259fb759
license    :
    - LGPL-2.0-or-later
component  : desktop.core
summary    : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description: |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
builddeps  :
    - pkgconfig(gudev-1.0)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libusb-1.0)
    - docbook-xml
    - gtk-doc
setup      : |
    %apply_patches
    %meson_configure -Didevice=enabled -Dgtk-doc=false -Dman=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -m 00644 $pkgfiles/upower.tmpfiles $installdir/%libdir%/tmpfiles.d/upower.conf
    rm -rvf $installdir/var
