name       : upower
version    : 0.99.17
release    : 17
source     :
    - https://gitlab.freedesktop.org/upower/upower/-/archive/v0.99.17/upower-v0.99.17.tar.gz : 14d91e98aa3a8c298e314b2df371c3dbe3ed9a0dab74b43678c38b27a67d555d
license    :
    - LGPL-2.0-or-later
component  : desktop.core
summary    : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description: |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
builddeps  :
    - pkgconfig(gudev-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libimobiledevice-1.0)
    - docbook-xml
    - gtk-doc
setup      : |
    %apply_patches
    %meson_configure -Didevice=enabled -Dgtk-doc=false -Dman=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -m 00644 $pkgfiles/upower.tmpfiles $installdir/%libdir%/tmpfiles.d/upower.conf
    rm -rvf $installdir/var
