name        : upower
version     : 0.99.4
release     : 7
source     :
    - https://upower.freedesktop.org/releases/upower-0.99.4.tar.xz : 9ca325a6ccef505529b268ebbbd9becd0ce65a65f6ac7ee31e2e5b17648037b0
license     :
    - LGPL-2.0
builddeps   :
    - pkgconfig(gudev-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libimobiledevice-1.0)
summary     : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description : |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
setup      : |
    %configure --disable-static \
               --disable-man-pages \
               --with-idevice
build      : |
    %make
install    : |
    %make_install
