name        : upower
version     : 0.99.3
release     : 6
source     :
    - http://upower.freedesktop.org/releases/upower-0.99.3.tar.xz : 697199bcc113bb069e6fb6bf4135536a702ba9847e46c5fc6df87d19624ddd38
license     :
    - LGPL-2.0
builddeps   :
    - pkgconfig(gudev-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libimobiledevice-1.0)
summary     : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description : |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
setup      : |
    %configure --disable-static \
               --disable-man-pages \
               --with-idevice
build      : |
    %make
install    : |
    %make_install
