name        : upower
version     : 0.99.4
release     : 9
source     :
    - git|https://anongit.freedesktop.org/git/upower.git : eb6b1b62a2733e380bdce7e3f7ef3726dc778c60
license     :
    - LGPL-2.0
builddeps   :
    - pkgconfig(gtk-doc)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libimobiledevice-1.0)
    - docbook-xml
component   : desktop.core
summary     : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description : |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
setup      : |
    %autogen --disable-static \
             --with-idevice
build      : |
    %make
install    : |
    %make_install
