name       : upower
version    : 0.99.7
release    : 10
source     :
    - https://upower.freedesktop.org/releases/upower-0.99.7.tar.xz : 24bcc2f6ab25a2533bac70b587bcb019e591293076920f5b5e04bdedc140a401
license    :
    - LGPL-2.0
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libimobiledevice-1.0)
    - docbook-xml
component  : desktop.core
summary    : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description: |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
setup      : |
    %apply_patches
    gtkdocize
    autopoint --force
    AUTOPOINT='intltoolize --automake --copy' autoreconf --force --install --verbose
    %configure --disable-static \
               --with-idevice
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/upower.tmpfiles $installdir/%libdir%/tmpfiles.d/upower.conf
    rm -rvf $installdir/var
