name       : upower
version    : 0.99.10
release    : 11
source     :
    - https://gitlab.freedesktop.org/upower/upower/uploads/c438511024b9bc5a904f8775cfc8e4c4/upower-0.99.10.tar.xz : 642251b97080ede8be6dbfeaf8f30ff6eadd6eb27aa137bc50f5b9b2295ba29d
license    :
    - LGPL-2.0
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libimobiledevice-1.0)
    - docbook-xml
component  : desktop.core
summary    : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description: |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
setup      : |
    %apply_patches
    gtkdocize
    autopoint --force
    AUTOPOINT='intltoolize --automake --copy' autoreconf --force --install --verbose
    %configure --disable-static \
               --with-idevice
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/upower.tmpfiles $installdir/%libdir%/tmpfiles.d/upower.conf
    rm -rvf $installdir/var
